[package]
name = "svarog_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
prost-types = "0.12"
tonic = { version = "0.10", features = ["gzip", "channel"] }
serde = { version = "1", features = ["derive"] }
